grails-app/domain/com/shqiperia/entities/ChildrensEvent.groovy
package com.shqiperia.entities

class ChildrensEvent extends Event {
	String additionalType="http://schema.org/ChildrensEvent"
	static constraints = {
	}
}

grails-app/controllers/com/shqiperia/entities/ChildrensEventController.groovy
package com.shqiperia.entities



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ChildrensEventController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond ChildrensEvent.list(params), model:[childrensEventInstanceCount: ChildrensEvent.count()]
    }

    def show(ChildrensEvent childrensEventInstance) {
        respond childrensEventInstance
    }

    def create() {
        respond new ChildrensEvent(params)
    }

    @Transactional
    def save(ChildrensEvent childrensEventInstance) {
        if (childrensEventInstance == null) {
            notFound()
            return
        }

        if (childrensEventInstance.hasErrors()) {
            respond childrensEventInstance.errors, view:'create'
            return
        }

        childrensEventInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'childrensEventInstance.label', default: 'ChildrensEvent'), childrensEventInstance.id])
                redirect childrensEventInstance
            }
            '*' { respond childrensEventInstance, [status: CREATED] }
        }
    }

    def edit(ChildrensEvent childrensEventInstance) {
        respond childrensEventInstance
    }

    @Transactional
    def update(ChildrensEvent childrensEventInstance) {
        if (childrensEventInstance == null) {
            notFound()
            return
        }

        if (childrensEventInstance.hasErrors()) {
            respond childrensEventInstance.errors, view:'edit'
            return
        }

        childrensEventInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'ChildrensEvent.label', default: 'ChildrensEvent'), childrensEventInstance.id])
                redirect childrensEventInstance
            }
            '*'{ respond childrensEventInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(ChildrensEvent childrensEventInstance) {

        if (childrensEventInstance == null) {
            notFound()
            return
        }

        childrensEventInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'ChildrensEvent.label', default: 'ChildrensEvent'), childrensEventInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'childrensEventInstance.label', default: 'ChildrensEvent'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/childrensEvent/_form.gsp
<%@ page import="com.shqiperia.entities.ChildrensEvent" %>



<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'name', 'error')} ">
	<label for="name">
		<g:message code="childrensEvent.name.label" default="Name" />
		
	</label>
	<g:textField name="name" maxlength="250" value="${childrensEventInstance?.name}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'additionalType', 'error')} ">
	<label for="additionalType">
		<g:message code="childrensEvent.additionalType.label" default="Additional Type" />
		
	</label>
	<g:textField name="additionalType" maxlength="250" value="${childrensEventInstance?.additionalType}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'alternateName', 'error')} ">
	<label for="alternateName">
		<g:message code="childrensEvent.alternateName.label" default="Alternate Name" />
		
	</label>
	<g:textField name="alternateName" maxlength="250" value="${childrensEventInstance?.alternateName}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'attendee', 'error')} ">
	<label for="attendee">
		<g:message code="childrensEvent.attendee.label" default="Attendee" />
		
	</label>
	<g:select name="attendee" from="${com.shqiperia.entities.Person.list()}" multiple="multiple" optionKey="id" size="5" value="${childrensEventInstance?.attendee*.id}" class="many-to-many"/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="childrensEvent.description.label" default="Description" />
		
	</label>
	<g:textField name="description" maxlength="250" value="${childrensEventInstance?.description}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'doorTime', 'error')} ">
	<label for="doorTime">
		<g:message code="childrensEvent.doorTime.label" default="Door Time" />
		
	</label>
	<g:datePicker name="doorTime" precision="day"  value="${childrensEventInstance?.doorTime}" default="none" noSelection="['': '']" />
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'duration', 'error')} ">
	<label for="duration">
		<g:message code="childrensEvent.duration.label" default="Duration" />
		
	</label>
	<g:datePicker name="duration" precision="day"  value="${childrensEventInstance?.duration}" default="none" noSelection="['': '']" />
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'endDate', 'error')} ">
	<label for="endDate">
		<g:message code="childrensEvent.endDate.label" default="End Date" />
		
	</label>
	<g:datePicker name="endDate" precision="day"  value="${childrensEventInstance?.endDate}" default="none" noSelection="['': '']" />
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'eventStatus', 'error')} ">
	<label for="eventStatus">
		<g:message code="childrensEvent.eventStatus.label" default="Event Status" />
		
	</label>
	<g:select name="eventStatus" from="${com.shqiperia.entities.Event$EventStatusType?.values()}" keys="${com.shqiperia.entities.Event$EventStatusType.values()*.name()}" value="${childrensEventInstance?.eventStatus?.name()}" noSelection="['': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'image', 'error')} ">
	<label for="image">
		<g:message code="childrensEvent.image.label" default="Image" />
		
	</label>
	<g:textField name="image" maxlength="250" value="${childrensEventInstance?.image}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'location', 'error')} ">
	<label for="location">
		<g:message code="childrensEvent.location.label" default="Location" />
		
	</label>
	<g:select id="location" name="location.id" from="${com.shqiperia.entities.Postaladdress.list()}" optionKey="id" value="${childrensEventInstance?.location?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'performer', 'error')} ">
	<label for="performer">
		<g:message code="childrensEvent.performer.label" default="Performer" />
		
	</label>
	<g:select name="performer" from="${com.shqiperia.entities.Person.list()}" multiple="multiple" optionKey="id" size="5" value="${childrensEventInstance?.performer*.id}" class="many-to-many"/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'previousStartDate', 'error')} ">
	<label for="previousStartDate">
		<g:message code="childrensEvent.previousStartDate.label" default="Previous Start Date" />
		
	</label>
	<g:datePicker name="previousStartDate" precision="day"  value="${childrensEventInstance?.previousStartDate}" default="none" noSelection="['': '']" />
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'sameAs', 'error')} ">
	<label for="sameAs">
		<g:message code="childrensEvent.sameAs.label" default="Same As" />
		
	</label>
	<g:textField name="sameAs" maxlength="250" value="${childrensEventInstance?.sameAs}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'startDate', 'error')} ">
	<label for="startDate">
		<g:message code="childrensEvent.startDate.label" default="Start Date" />
		
	</label>
	<g:datePicker name="startDate" precision="day"  value="${childrensEventInstance?.startDate}" default="none" noSelection="['': '']" />
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'subEvent', 'error')} ">
	<label for="subEvent">
		<g:message code="childrensEvent.subEvent.label" default="Sub Event" />
		
	</label>
	
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'superEvent', 'error')} ">
	<label for="superEvent">
		<g:message code="childrensEvent.superEvent.label" default="Super Event" />
		
	</label>
	
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'typicalAgeRange', 'error')} ">
	<label for="typicalAgeRange">
		<g:message code="childrensEvent.typicalAgeRange.label" default="Typical Age Range" />
		
	</label>
	<g:textField name="typicalAgeRange" maxlength="250" value="${childrensEventInstance?.typicalAgeRange}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrensEventInstance, field: 'url', 'error')} ">
	<label for="url">
		<g:message code="childrensEvent.url.label" default="Url" />
		
	</label>
	<g:textField name="url" maxlength="250" value="${childrensEventInstance?.url}"/>
</div>

grails-app/views/childrensEvent/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'childrensEvent.label', default: 'ChildrensEvent')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-childrensEvent" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-childrensEvent" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${childrensEventInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${childrensEventInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:childrensEventInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/childrensEvent/edit.gsp
<%@ page import="com.shqiperia.entities.ChildrensEvent" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'childrensEvent.label', default: 'ChildrensEvent')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-childrensEvent" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-childrensEvent" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${childrensEventInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${childrensEventInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:childrensEventInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${childrensEventInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/childrensEvent/index.gsp
<%@ page import="com.shqiperia.entities.ChildrensEvent" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'childrensEvent.label', default: 'ChildrensEvent')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-childrensEvent" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-childrensEvent" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'childrensEvent.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="additionalType" title="${message(code: 'childrensEvent.additionalType.label', default: 'Additional Type')}" />
					
						<g:sortableColumn property="alternateName" title="${message(code: 'childrensEvent.alternateName.label', default: 'Alternate Name')}" />
					
						<g:sortableColumn property="description" title="${message(code: 'childrensEvent.description.label', default: 'Description')}" />
					
						<g:sortableColumn property="doorTime" title="${message(code: 'childrensEvent.doorTime.label', default: 'Door Time')}" />
					
						<g:sortableColumn property="duration" title="${message(code: 'childrensEvent.duration.label', default: 'Duration')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${childrensEventInstanceList}" status="i" var="childrensEventInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${childrensEventInstance.id}">${fieldValue(bean: childrensEventInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: childrensEventInstance, field: "additionalType")}</td>
					
						<td>${fieldValue(bean: childrensEventInstance, field: "alternateName")}</td>
					
						<td>${fieldValue(bean: childrensEventInstance, field: "description")}</td>
					
						<td><g:formatDate date="${childrensEventInstance.doorTime}" /></td>
					
						<td><g:formatDate date="${childrensEventInstance.duration}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${childrensEventInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/childrensEvent/show.gsp
<%@ page import="com.shqiperia.entities.ChildrensEvent" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'childrensEvent.label', default: 'ChildrensEvent')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-childrensEvent" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-childrensEvent" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list childrensEvent">
			
				<g:if test="${childrensEventInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="childrensEvent.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${childrensEventInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.additionalType}">
				<li class="fieldcontain">
					<span id="additionalType-label" class="property-label"><g:message code="childrensEvent.additionalType.label" default="Additional Type" /></span>
					
						<span class="property-value" aria-labelledby="additionalType-label"><g:fieldValue bean="${childrensEventInstance}" field="additionalType"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.alternateName}">
				<li class="fieldcontain">
					<span id="alternateName-label" class="property-label"><g:message code="childrensEvent.alternateName.label" default="Alternate Name" /></span>
					
						<span class="property-value" aria-labelledby="alternateName-label"><g:fieldValue bean="${childrensEventInstance}" field="alternateName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.attendee}">
				<li class="fieldcontain">
					<span id="attendee-label" class="property-label"><g:message code="childrensEvent.attendee.label" default="Attendee" /></span>
					
						<g:each in="${childrensEventInstance.attendee}" var="a">
						<span class="property-value" aria-labelledby="attendee-label"><g:link controller="person" action="show" id="${a.id}">${a?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="childrensEvent.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${childrensEventInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.doorTime}">
				<li class="fieldcontain">
					<span id="doorTime-label" class="property-label"><g:message code="childrensEvent.doorTime.label" default="Door Time" /></span>
					
						<span class="property-value" aria-labelledby="doorTime-label"><g:formatDate date="${childrensEventInstance?.doorTime}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.duration}">
				<li class="fieldcontain">
					<span id="duration-label" class="property-label"><g:message code="childrensEvent.duration.label" default="Duration" /></span>
					
						<span class="property-value" aria-labelledby="duration-label"><g:formatDate date="${childrensEventInstance?.duration}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.endDate}">
				<li class="fieldcontain">
					<span id="endDate-label" class="property-label"><g:message code="childrensEvent.endDate.label" default="End Date" /></span>
					
						<span class="property-value" aria-labelledby="endDate-label"><g:formatDate date="${childrensEventInstance?.endDate}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.eventStatus}">
				<li class="fieldcontain">
					<span id="eventStatus-label" class="property-label"><g:message code="childrensEvent.eventStatus.label" default="Event Status" /></span>
					
						<span class="property-value" aria-labelledby="eventStatus-label"><g:fieldValue bean="${childrensEventInstance}" field="eventStatus"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.image}">
				<li class="fieldcontain">
					<span id="image-label" class="property-label"><g:message code="childrensEvent.image.label" default="Image" /></span>
					
						<span class="property-value" aria-labelledby="image-label"><g:fieldValue bean="${childrensEventInstance}" field="image"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.location}">
				<li class="fieldcontain">
					<span id="location-label" class="property-label"><g:message code="childrensEvent.location.label" default="Location" /></span>
					
						<span class="property-value" aria-labelledby="location-label"><g:link controller="postaladdress" action="show" id="${childrensEventInstance?.location?.id}">${childrensEventInstance?.location?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.performer}">
				<li class="fieldcontain">
					<span id="performer-label" class="property-label"><g:message code="childrensEvent.performer.label" default="Performer" /></span>
					
						<g:each in="${childrensEventInstance.performer}" var="p">
						<span class="property-value" aria-labelledby="performer-label"><g:link controller="person" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.previousStartDate}">
				<li class="fieldcontain">
					<span id="previousStartDate-label" class="property-label"><g:message code="childrensEvent.previousStartDate.label" default="Previous Start Date" /></span>
					
						<span class="property-value" aria-labelledby="previousStartDate-label"><g:formatDate date="${childrensEventInstance?.previousStartDate}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.sameAs}">
				<li class="fieldcontain">
					<span id="sameAs-label" class="property-label"><g:message code="childrensEvent.sameAs.label" default="Same As" /></span>
					
						<span class="property-value" aria-labelledby="sameAs-label"><g:fieldValue bean="${childrensEventInstance}" field="sameAs"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.startDate}">
				<li class="fieldcontain">
					<span id="startDate-label" class="property-label"><g:message code="childrensEvent.startDate.label" default="Start Date" /></span>
					
						<span class="property-value" aria-labelledby="startDate-label"><g:formatDate date="${childrensEventInstance?.startDate}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.subEvent}">
				<li class="fieldcontain">
					<span id="subEvent-label" class="property-label"><g:message code="childrensEvent.subEvent.label" default="Sub Event" /></span>
					
						<g:each in="${childrensEventInstance.subEvent}" var="s">
						<span class="property-value" aria-labelledby="subEvent-label"><g:link controller="event" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.superEvent}">
				<li class="fieldcontain">
					<span id="superEvent-label" class="property-label"><g:message code="childrensEvent.superEvent.label" default="Super Event" /></span>
					
						<g:each in="${childrensEventInstance.superEvent}" var="s">
						<span class="property-value" aria-labelledby="superEvent-label"><g:link controller="event" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.typicalAgeRange}">
				<li class="fieldcontain">
					<span id="typicalAgeRange-label" class="property-label"><g:message code="childrensEvent.typicalAgeRange.label" default="Typical Age Range" /></span>
					
						<span class="property-value" aria-labelledby="typicalAgeRange-label"><g:fieldValue bean="${childrensEventInstance}" field="typicalAgeRange"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrensEventInstance?.url}">
				<li class="fieldcontain">
					<span id="url-label" class="property-label"><g:message code="childrensEvent.url.label" default="Url" /></span>
					
						<span class="property-value" aria-labelledby="url-label"><g:fieldValue bean="${childrensEventInstance}" field="url"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:childrensEventInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${childrensEventInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>