grails-app/domain/com/shqiperia/entities/LiteraryEvent.groovy
package com.shqiperia.entities

class LiteraryEvent extends Event{
	String additionalType="http://schema.org/BusinessEvent"

    static constraints = {
    }
}

grails-app/controllers/com/shqiperia/entities/LiteraryEventController.groovy
package com.shqiperia.entities



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class LiteraryEventController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond LiteraryEvent.list(params), model:[literaryEventInstanceCount: LiteraryEvent.count()]
    }

    def show(LiteraryEvent literaryEventInstance) {
        respond literaryEventInstance
    }

    def create() {
        respond new LiteraryEvent(params)
    }

    @Transactional
    def save(LiteraryEvent literaryEventInstance) {
        if (literaryEventInstance == null) {
            notFound()
            return
        }

        if (literaryEventInstance.hasErrors()) {
            respond literaryEventInstance.errors, view:'create'
            return
        }

        literaryEventInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'literaryEventInstance.label', default: 'LiteraryEvent'), literaryEventInstance.id])
                redirect literaryEventInstance
            }
            '*' { respond literaryEventInstance, [status: CREATED] }
        }
    }

    def edit(LiteraryEvent literaryEventInstance) {
        respond literaryEventInstance
    }

    @Transactional
    def update(LiteraryEvent literaryEventInstance) {
        if (literaryEventInstance == null) {
            notFound()
            return
        }

        if (literaryEventInstance.hasErrors()) {
            respond literaryEventInstance.errors, view:'edit'
            return
        }

        literaryEventInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'LiteraryEvent.label', default: 'LiteraryEvent'), literaryEventInstance.id])
                redirect literaryEventInstance
            }
            '*'{ respond literaryEventInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(LiteraryEvent literaryEventInstance) {

        if (literaryEventInstance == null) {
            notFound()
            return
        }

        literaryEventInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'LiteraryEvent.label', default: 'LiteraryEvent'), literaryEventInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'literaryEventInstance.label', default: 'LiteraryEvent'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/literaryEvent/_form.gsp
<%@ page import="com.shqiperia.entities.LiteraryEvent" %>



<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'name', 'error')} ">
	<label for="name">
		<g:message code="literaryEvent.name.label" default="Name" />
		
	</label>
	<g:textField name="name" maxlength="250" value="${literaryEventInstance?.name}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'additionalType', 'error')} ">
	<label for="additionalType">
		<g:message code="literaryEvent.additionalType.label" default="Additional Type" />
		
	</label>
	<g:textField name="additionalType" maxlength="250" value="${literaryEventInstance?.additionalType}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'alternateName', 'error')} ">
	<label for="alternateName">
		<g:message code="literaryEvent.alternateName.label" default="Alternate Name" />
		
	</label>
	<g:textField name="alternateName" maxlength="250" value="${literaryEventInstance?.alternateName}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'attendee', 'error')} ">
	<label for="attendee">
		<g:message code="literaryEvent.attendee.label" default="Attendee" />
		
	</label>
	<g:select name="attendee" from="${com.shqiperia.entities.Person.list()}" multiple="multiple" optionKey="id" size="5" value="${literaryEventInstance?.attendee*.id}" class="many-to-many"/>
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="literaryEvent.description.label" default="Description" />
		
	</label>
	<g:textField name="description" maxlength="250" value="${literaryEventInstance?.description}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'doorTime', 'error')} ">
	<label for="doorTime">
		<g:message code="literaryEvent.doorTime.label" default="Door Time" />
		
	</label>
	<g:datePicker name="doorTime" precision="day"  value="${literaryEventInstance?.doorTime}" default="none" noSelection="['': '']" />
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'duration', 'error')} ">
	<label for="duration">
		<g:message code="literaryEvent.duration.label" default="Duration" />
		
	</label>
	<g:datePicker name="duration" precision="day"  value="${literaryEventInstance?.duration}" default="none" noSelection="['': '']" />
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'endDate', 'error')} ">
	<label for="endDate">
		<g:message code="literaryEvent.endDate.label" default="End Date" />
		
	</label>
	<g:datePicker name="endDate" precision="day"  value="${literaryEventInstance?.endDate}" default="none" noSelection="['': '']" />
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'eventStatus', 'error')} ">
	<label for="eventStatus">
		<g:message code="literaryEvent.eventStatus.label" default="Event Status" />
		
	</label>
	<g:select name="eventStatus" from="${com.shqiperia.entities.Event$EventStatusType?.values()}" keys="${com.shqiperia.entities.Event$EventStatusType.values()*.name()}" value="${literaryEventInstance?.eventStatus?.name()}" noSelection="['': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'image', 'error')} ">
	<label for="image">
		<g:message code="literaryEvent.image.label" default="Image" />
		
	</label>
	<g:textField name="image" maxlength="250" value="${literaryEventInstance?.image}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'location', 'error')} ">
	<label for="location">
		<g:message code="literaryEvent.location.label" default="Location" />
		
	</label>
	<g:select id="location" name="location.id" from="${com.shqiperia.entities.Postaladdress.list()}" optionKey="id" value="${literaryEventInstance?.location?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'performer', 'error')} ">
	<label for="performer">
		<g:message code="literaryEvent.performer.label" default="Performer" />
		
	</label>
	<g:select name="performer" from="${com.shqiperia.entities.Person.list()}" multiple="multiple" optionKey="id" size="5" value="${literaryEventInstance?.performer*.id}" class="many-to-many"/>
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'previousStartDate', 'error')} ">
	<label for="previousStartDate">
		<g:message code="literaryEvent.previousStartDate.label" default="Previous Start Date" />
		
	</label>
	<g:datePicker name="previousStartDate" precision="day"  value="${literaryEventInstance?.previousStartDate}" default="none" noSelection="['': '']" />
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'sameAs', 'error')} ">
	<label for="sameAs">
		<g:message code="literaryEvent.sameAs.label" default="Same As" />
		
	</label>
	<g:textField name="sameAs" maxlength="250" value="${literaryEventInstance?.sameAs}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'startDate', 'error')} ">
	<label for="startDate">
		<g:message code="literaryEvent.startDate.label" default="Start Date" />
		
	</label>
	<g:datePicker name="startDate" precision="day"  value="${literaryEventInstance?.startDate}" default="none" noSelection="['': '']" />
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'subEvent', 'error')} ">
	<label for="subEvent">
		<g:message code="literaryEvent.subEvent.label" default="Sub Event" />
		
	</label>
	
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'superEvent', 'error')} ">
	<label for="superEvent">
		<g:message code="literaryEvent.superEvent.label" default="Super Event" />
		
	</label>
	
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'typicalAgeRange', 'error')} ">
	<label for="typicalAgeRange">
		<g:message code="literaryEvent.typicalAgeRange.label" default="Typical Age Range" />
		
	</label>
	<g:textField name="typicalAgeRange" maxlength="250" value="${literaryEventInstance?.typicalAgeRange}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: literaryEventInstance, field: 'url', 'error')} ">
	<label for="url">
		<g:message code="literaryEvent.url.label" default="Url" />
		
	</label>
	<g:textField name="url" maxlength="250" value="${literaryEventInstance?.url}"/>
</div>

grails-app/views/literaryEvent/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'literaryEvent.label', default: 'LiteraryEvent')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-literaryEvent" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-literaryEvent" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${literaryEventInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${literaryEventInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:literaryEventInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/literaryEvent/edit.gsp
<%@ page import="com.shqiperia.entities.LiteraryEvent" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'literaryEvent.label', default: 'LiteraryEvent')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-literaryEvent" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-literaryEvent" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${literaryEventInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${literaryEventInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:literaryEventInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${literaryEventInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/literaryEvent/index.gsp
<%@ page import="com.shqiperia.entities.LiteraryEvent" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'literaryEvent.label', default: 'LiteraryEvent')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-literaryEvent" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-literaryEvent" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'literaryEvent.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="additionalType" title="${message(code: 'literaryEvent.additionalType.label', default: 'Additional Type')}" />
					
						<g:sortableColumn property="alternateName" title="${message(code: 'literaryEvent.alternateName.label', default: 'Alternate Name')}" />
					
						<g:sortableColumn property="description" title="${message(code: 'literaryEvent.description.label', default: 'Description')}" />
					
						<g:sortableColumn property="doorTime" title="${message(code: 'literaryEvent.doorTime.label', default: 'Door Time')}" />
					
						<g:sortableColumn property="duration" title="${message(code: 'literaryEvent.duration.label', default: 'Duration')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${literaryEventInstanceList}" status="i" var="literaryEventInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${literaryEventInstance.id}">${fieldValue(bean: literaryEventInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: literaryEventInstance, field: "additionalType")}</td>
					
						<td>${fieldValue(bean: literaryEventInstance, field: "alternateName")}</td>
					
						<td>${fieldValue(bean: literaryEventInstance, field: "description")}</td>
					
						<td><g:formatDate date="${literaryEventInstance.doorTime}" /></td>
					
						<td><g:formatDate date="${literaryEventInstance.duration}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${literaryEventInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/literaryEvent/show.gsp
<%@ page import="com.shqiperia.entities.LiteraryEvent" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'literaryEvent.label', default: 'LiteraryEvent')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-literaryEvent" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-literaryEvent" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list literaryEvent">
			
				<g:if test="${literaryEventInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="literaryEvent.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${literaryEventInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.additionalType}">
				<li class="fieldcontain">
					<span id="additionalType-label" class="property-label"><g:message code="literaryEvent.additionalType.label" default="Additional Type" /></span>
					
						<span class="property-value" aria-labelledby="additionalType-label"><g:fieldValue bean="${literaryEventInstance}" field="additionalType"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.alternateName}">
				<li class="fieldcontain">
					<span id="alternateName-label" class="property-label"><g:message code="literaryEvent.alternateName.label" default="Alternate Name" /></span>
					
						<span class="property-value" aria-labelledby="alternateName-label"><g:fieldValue bean="${literaryEventInstance}" field="alternateName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.attendee}">
				<li class="fieldcontain">
					<span id="attendee-label" class="property-label"><g:message code="literaryEvent.attendee.label" default="Attendee" /></span>
					
						<g:each in="${literaryEventInstance.attendee}" var="a">
						<span class="property-value" aria-labelledby="attendee-label"><g:link controller="person" action="show" id="${a.id}">${a?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="literaryEvent.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${literaryEventInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.doorTime}">
				<li class="fieldcontain">
					<span id="doorTime-label" class="property-label"><g:message code="literaryEvent.doorTime.label" default="Door Time" /></span>
					
						<span class="property-value" aria-labelledby="doorTime-label"><g:formatDate date="${literaryEventInstance?.doorTime}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.duration}">
				<li class="fieldcontain">
					<span id="duration-label" class="property-label"><g:message code="literaryEvent.duration.label" default="Duration" /></span>
					
						<span class="property-value" aria-labelledby="duration-label"><g:formatDate date="${literaryEventInstance?.duration}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.endDate}">
				<li class="fieldcontain">
					<span id="endDate-label" class="property-label"><g:message code="literaryEvent.endDate.label" default="End Date" /></span>
					
						<span class="property-value" aria-labelledby="endDate-label"><g:formatDate date="${literaryEventInstance?.endDate}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.eventStatus}">
				<li class="fieldcontain">
					<span id="eventStatus-label" class="property-label"><g:message code="literaryEvent.eventStatus.label" default="Event Status" /></span>
					
						<span class="property-value" aria-labelledby="eventStatus-label"><g:fieldValue bean="${literaryEventInstance}" field="eventStatus"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.image}">
				<li class="fieldcontain">
					<span id="image-label" class="property-label"><g:message code="literaryEvent.image.label" default="Image" /></span>
					
						<span class="property-value" aria-labelledby="image-label"><g:fieldValue bean="${literaryEventInstance}" field="image"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.location}">
				<li class="fieldcontain">
					<span id="location-label" class="property-label"><g:message code="literaryEvent.location.label" default="Location" /></span>
					
						<span class="property-value" aria-labelledby="location-label"><g:link controller="postaladdress" action="show" id="${literaryEventInstance?.location?.id}">${literaryEventInstance?.location?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.performer}">
				<li class="fieldcontain">
					<span id="performer-label" class="property-label"><g:message code="literaryEvent.performer.label" default="Performer" /></span>
					
						<g:each in="${literaryEventInstance.performer}" var="p">
						<span class="property-value" aria-labelledby="performer-label"><g:link controller="person" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.previousStartDate}">
				<li class="fieldcontain">
					<span id="previousStartDate-label" class="property-label"><g:message code="literaryEvent.previousStartDate.label" default="Previous Start Date" /></span>
					
						<span class="property-value" aria-labelledby="previousStartDate-label"><g:formatDate date="${literaryEventInstance?.previousStartDate}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.sameAs}">
				<li class="fieldcontain">
					<span id="sameAs-label" class="property-label"><g:message code="literaryEvent.sameAs.label" default="Same As" /></span>
					
						<span class="property-value" aria-labelledby="sameAs-label"><g:fieldValue bean="${literaryEventInstance}" field="sameAs"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.startDate}">
				<li class="fieldcontain">
					<span id="startDate-label" class="property-label"><g:message code="literaryEvent.startDate.label" default="Start Date" /></span>
					
						<span class="property-value" aria-labelledby="startDate-label"><g:formatDate date="${literaryEventInstance?.startDate}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.subEvent}">
				<li class="fieldcontain">
					<span id="subEvent-label" class="property-label"><g:message code="literaryEvent.subEvent.label" default="Sub Event" /></span>
					
						<g:each in="${literaryEventInstance.subEvent}" var="s">
						<span class="property-value" aria-labelledby="subEvent-label"><g:link controller="event" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.superEvent}">
				<li class="fieldcontain">
					<span id="superEvent-label" class="property-label"><g:message code="literaryEvent.superEvent.label" default="Super Event" /></span>
					
						<g:each in="${literaryEventInstance.superEvent}" var="s">
						<span class="property-value" aria-labelledby="superEvent-label"><g:link controller="event" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.typicalAgeRange}">
				<li class="fieldcontain">
					<span id="typicalAgeRange-label" class="property-label"><g:message code="literaryEvent.typicalAgeRange.label" default="Typical Age Range" /></span>
					
						<span class="property-value" aria-labelledby="typicalAgeRange-label"><g:fieldValue bean="${literaryEventInstance}" field="typicalAgeRange"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${literaryEventInstance?.url}">
				<li class="fieldcontain">
					<span id="url-label" class="property-label"><g:message code="literaryEvent.url.label" default="Url" /></span>
					
						<span class="property-value" aria-labelledby="url-label"><g:fieldValue bean="${literaryEventInstance}" field="url"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:literaryEventInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${literaryEventInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>