grails-app/domain/com/shqiperia/entities/VideoObject.groovy
package com.shqiperia.entities

class VideoObject extends MediaObject{

    String additionalType="http://schema.org/VideoObject"
    
    String caption     //Text    The caption for this object.
    String thumbnail   //ImageObject     Thumbnail image for an image or video.
    String transcript  //Text    If this MediaObject is an AudioObject or VideoObject, the transcript of that object.
    String videoFrameSize  //Text    The frame size of the video.
    String videoQuality    //Text    The quality of the video.

    static constraints = {
    }
}

grails-app/controllers/com/shqiperia/entities/VideoObjectController.groovy
package com.shqiperia.entities



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class VideoObjectController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond VideoObject.list(params), model:[videoObjectInstanceCount: VideoObject.count()]
    }

    def show(VideoObject videoObjectInstance) {
        respond videoObjectInstance
    }

    def create() {
        respond new VideoObject(params)
    }

    @Transactional
    def save(VideoObject videoObjectInstance) {
        if (videoObjectInstance == null) {
            notFound()
            return
        }

        if (videoObjectInstance.hasErrors()) {
            respond videoObjectInstance.errors, view:'create'
            return
        }

        videoObjectInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'videoObjectInstance.label', default: 'VideoObject'), videoObjectInstance.id])
                redirect videoObjectInstance
            }
            '*' { respond videoObjectInstance, [status: CREATED] }
        }
    }

    def edit(VideoObject videoObjectInstance) {
        respond videoObjectInstance
    }

    @Transactional
    def update(VideoObject videoObjectInstance) {
        if (videoObjectInstance == null) {
            notFound()
            return
        }

        if (videoObjectInstance.hasErrors()) {
            respond videoObjectInstance.errors, view:'edit'
            return
        }

        videoObjectInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'VideoObject.label', default: 'VideoObject'), videoObjectInstance.id])
                redirect videoObjectInstance
            }
            '*'{ respond videoObjectInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(VideoObject videoObjectInstance) {

        if (videoObjectInstance == null) {
            notFound()
            return
        }

        videoObjectInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'VideoObject.label', default: 'VideoObject'), videoObjectInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'videoObjectInstance.label', default: 'VideoObject'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/videoObject/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'videoObject.label', default: 'VideoObject')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-videoObject" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-videoObject" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${videoObjectInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${videoObjectInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:videoObjectInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/videoObject/edit.gsp
<%@ page import="com.shqiperia.entities.VideoObject" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'videoObject.label', default: 'VideoObject')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-videoObject" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-videoObject" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${videoObjectInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${videoObjectInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:videoObjectInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${videoObjectInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/videoObject/index.gsp
<%@ page import="com.shqiperia.entities.VideoObject" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'videoObject.label', default: 'VideoObject')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-videoObject" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-videoObject" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="about" title="${message(code: 'videoObject.about.label', default: 'About')}" />
					
						<g:sortableColumn property="accessibilityAPI" title="${message(code: 'videoObject.accessibilityAPI.label', default: 'Accessibility API')}" />
					
						<g:sortableColumn property="accessibilityControl" title="${message(code: 'videoObject.accessibilityControl.label', default: 'Accessibility Control')}" />
					
						<g:sortableColumn property="accessibilityFeature" title="${message(code: 'videoObject.accessibilityFeature.label', default: 'Accessibility Feature')}" />
					
						<g:sortableColumn property="accessibilityHazard" title="${message(code: 'videoObject.accessibilityHazard.label', default: 'Accessibility Hazard')}" />
					
						<g:sortableColumn property="additionalType" title="${message(code: 'videoObject.additionalType.label', default: 'Additional Type')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${videoObjectInstanceList}" status="i" var="videoObjectInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${videoObjectInstance.id}">${fieldValue(bean: videoObjectInstance, field: "about")}</g:link></td>
					
						<td>${fieldValue(bean: videoObjectInstance, field: "accessibilityAPI")}</td>
					
						<td>${fieldValue(bean: videoObjectInstance, field: "accessibilityControl")}</td>
					
						<td>${fieldValue(bean: videoObjectInstance, field: "accessibilityFeature")}</td>
					
						<td>${fieldValue(bean: videoObjectInstance, field: "accessibilityHazard")}</td>
					
						<td>${fieldValue(bean: videoObjectInstance, field: "additionalType")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${videoObjectInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>