grails-app/domain/com/shqiperia/entities/PriceSpecification.groovy
package com.shqiperia.entities

class PriceSpecification extends StructuredValue {
    String additionalType="http://schema.org/StructuredValue"
    QuantitativeValue eligibleQuantity   // QuantitativeValue   The interval and unit of measurement of ordering quantities for which the offer or price specification is valid. This allows e.g. specifying that a certain freight charge is valid only for a certain quantity.
    PriceSpecification eligibleTransactionVolume   //PriceSpecification  The transaction volume, in a monetary unit, for which the offer or price specification is valid, e.g. for indicating a minimal purchasing volume, to express free shipping above a certain order volume, or to limit the acceptance of credit cards to purchases to a certain minimal amount.
    Float maxPrice    //Number  The highest price if the price is a range.
    Float minPrice    //Number  The lowest price if the price is a range.
    Float price   //Number or Text  The offer price of a product, or of a price component when attached to PriceSpecification and its subtypes.
    String priceCurrency   //Text    The currency (in 3-letter ISO 4217 format) of the offer price or a price component, when attached to PriceSpecification and its subtypes.
    Date validFrom   //DateTime    The date when the item becomes valid.
    Date validThrough    //DateTime    The end of the validity of offer, price specification, or opening hours data.
    boolean valueAddedTaxIncluded   //Boolean     Specifies whether the applicable value-added tax (VAT) is included in the price specification or not.

    static constraints = {
    }
}

grails-app/controllers/com/shqiperia/entities/PriceSpecificationController.groovy
package com.shqiperia.entities



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class PriceSpecificationController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond PriceSpecification.list(params), model:[priceSpecificationInstanceCount: PriceSpecification.count()]
    }

    def show(PriceSpecification priceSpecificationInstance) {
        respond priceSpecificationInstance
    }

    def create() {
        respond new PriceSpecification(params)
    }

    @Transactional
    def save(PriceSpecification priceSpecificationInstance) {
        if (priceSpecificationInstance == null) {
            notFound()
            return
        }

        if (priceSpecificationInstance.hasErrors()) {
            respond priceSpecificationInstance.errors, view:'create'
            return
        }

        priceSpecificationInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'priceSpecificationInstance.label', default: 'PriceSpecification'), priceSpecificationInstance.id])
                redirect priceSpecificationInstance
            }
            '*' { respond priceSpecificationInstance, [status: CREATED] }
        }
    }

    def edit(PriceSpecification priceSpecificationInstance) {
        respond priceSpecificationInstance
    }

    @Transactional
    def update(PriceSpecification priceSpecificationInstance) {
        if (priceSpecificationInstance == null) {
            notFound()
            return
        }

        if (priceSpecificationInstance.hasErrors()) {
            respond priceSpecificationInstance.errors, view:'edit'
            return
        }

        priceSpecificationInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'PriceSpecification.label', default: 'PriceSpecification'), priceSpecificationInstance.id])
                redirect priceSpecificationInstance
            }
            '*'{ respond priceSpecificationInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(PriceSpecification priceSpecificationInstance) {

        if (priceSpecificationInstance == null) {
            notFound()
            return
        }

        priceSpecificationInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'PriceSpecification.label', default: 'PriceSpecification'), priceSpecificationInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'priceSpecificationInstance.label', default: 'PriceSpecification'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/priceSpecification/_form.gsp
<%@ page import="com.shqiperia.entities.PriceSpecification" %>



<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'additionalType', 'error')} ">
	<label for="additionalType">
		<g:message code="priceSpecification.additionalType.label" default="Additional Type" />
		
	</label>
	<g:textField name="additionalType" maxlength="250" value="${priceSpecificationInstance?.additionalType}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'alternateName', 'error')} ">
	<label for="alternateName">
		<g:message code="priceSpecification.alternateName.label" default="Alternate Name" />
		
	</label>
	<g:textField name="alternateName" maxlength="250" value="${priceSpecificationInstance?.alternateName}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="priceSpecification.description.label" default="Description" />
		
	</label>
	<g:textField name="description" maxlength="250" value="${priceSpecificationInstance?.description}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'eligibleQuantity', 'error')} ">
	<label for="eligibleQuantity">
		<g:message code="priceSpecification.eligibleQuantity.label" default="Eligible Quantity" />
		
	</label>
	<g:select id="eligibleQuantity" name="eligibleQuantity.id" from="${com.shqiperia.entities.QuantitativeValue.list()}" optionKey="id" value="${priceSpecificationInstance?.eligibleQuantity?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'eligibleTransactionVolume', 'error')} required">
	<label for="eligibleTransactionVolume">
		<g:message code="priceSpecification.eligibleTransactionVolume.label" default="Eligible Transaction Volume" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="eligibleTransactionVolume" name="eligibleTransactionVolume.id" from="${com.shqiperia.entities.PriceSpecification.list()}" optionKey="id" required="" value="${priceSpecificationInstance?.eligibleTransactionVolume?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'image', 'error')} ">
	<label for="image">
		<g:message code="priceSpecification.image.label" default="Image" />
		
	</label>
	<g:textField name="image" maxlength="250" value="${priceSpecificationInstance?.image}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'maxPrice', 'error')} ">
	<label for="maxPrice">
		<g:message code="priceSpecification.maxPrice.label" default="Max Price" />
		
	</label>
	<g:field name="maxPrice" value="${fieldValue(bean: priceSpecificationInstance, field: 'maxPrice')}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'minPrice', 'error')} ">
	<label for="minPrice">
		<g:message code="priceSpecification.minPrice.label" default="Min Price" />
		
	</label>
	<g:field name="minPrice" value="${fieldValue(bean: priceSpecificationInstance, field: 'minPrice')}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'name', 'error')} ">
	<label for="name">
		<g:message code="priceSpecification.name.label" default="Name" />
		
	</label>
	<g:textField name="name" maxlength="250" value="${priceSpecificationInstance?.name}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'price', 'error')} ">
	<label for="price">
		<g:message code="priceSpecification.price.label" default="Price" />
		
	</label>
	<g:field name="price" value="${fieldValue(bean: priceSpecificationInstance, field: 'price')}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'priceCurrency', 'error')} ">
	<label for="priceCurrency">
		<g:message code="priceSpecification.priceCurrency.label" default="Price Currency" />
		
	</label>
	<g:textField name="priceCurrency" maxlength="250" value="${priceSpecificationInstance?.priceCurrency}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'sameAs', 'error')} ">
	<label for="sameAs">
		<g:message code="priceSpecification.sameAs.label" default="Same As" />
		
	</label>
	<g:textField name="sameAs" maxlength="250" value="${priceSpecificationInstance?.sameAs}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'url', 'error')} ">
	<label for="url">
		<g:message code="priceSpecification.url.label" default="Url" />
		
	</label>
	<g:textField name="url" maxlength="250" value="${priceSpecificationInstance?.url}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'validFrom', 'error')} ">
	<label for="validFrom">
		<g:message code="priceSpecification.validFrom.label" default="Valid From" />
		
	</label>
	<g:datePicker name="validFrom" precision="day"  value="${priceSpecificationInstance?.validFrom}" default="none" noSelection="['': '']" />
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'validThrough', 'error')} ">
	<label for="validThrough">
		<g:message code="priceSpecification.validThrough.label" default="Valid Through" />
		
	</label>
	<g:datePicker name="validThrough" precision="day"  value="${priceSpecificationInstance?.validThrough}" default="none" noSelection="['': '']" />
</div>

<div class="fieldcontain ${hasErrors(bean: priceSpecificationInstance, field: 'valueAddedTaxIncluded', 'error')} ">
	<label for="valueAddedTaxIncluded">
		<g:message code="priceSpecification.valueAddedTaxIncluded.label" default="Value Added Tax Included" />
		
	</label>
	<g:checkBox name="valueAddedTaxIncluded" value="${priceSpecificationInstance?.valueAddedTaxIncluded}" />
</div>

grails-app/views/priceSpecification/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'priceSpecification.label', default: 'PriceSpecification')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-priceSpecification" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-priceSpecification" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${priceSpecificationInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${priceSpecificationInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:priceSpecificationInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/priceSpecification/edit.gsp
<%@ page import="com.shqiperia.entities.PriceSpecification" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'priceSpecification.label', default: 'PriceSpecification')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-priceSpecification" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-priceSpecification" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${priceSpecificationInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${priceSpecificationInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:priceSpecificationInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${priceSpecificationInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/priceSpecification/index.gsp
<%@ page import="com.shqiperia.entities.PriceSpecification" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'priceSpecification.label', default: 'PriceSpecification')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-priceSpecification" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-priceSpecification" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="additionalType" title="${message(code: 'priceSpecification.additionalType.label', default: 'Additional Type')}" />
					
						<g:sortableColumn property="alternateName" title="${message(code: 'priceSpecification.alternateName.label', default: 'Alternate Name')}" />
					
						<g:sortableColumn property="description" title="${message(code: 'priceSpecification.description.label', default: 'Description')}" />
					
						<th><g:message code="priceSpecification.eligibleQuantity.label" default="Eligible Quantity" /></th>
					
						<th><g:message code="priceSpecification.eligibleTransactionVolume.label" default="Eligible Transaction Volume" /></th>
					
						<g:sortableColumn property="image" title="${message(code: 'priceSpecification.image.label', default: 'Image')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${priceSpecificationInstanceList}" status="i" var="priceSpecificationInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${priceSpecificationInstance.id}">${fieldValue(bean: priceSpecificationInstance, field: "additionalType")}</g:link></td>
					
						<td>${fieldValue(bean: priceSpecificationInstance, field: "alternateName")}</td>
					
						<td>${fieldValue(bean: priceSpecificationInstance, field: "description")}</td>
					
						<td>${fieldValue(bean: priceSpecificationInstance, field: "eligibleQuantity")}</td>
					
						<td>${fieldValue(bean: priceSpecificationInstance, field: "eligibleTransactionVolume")}</td>
					
						<td>${fieldValue(bean: priceSpecificationInstance, field: "image")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${priceSpecificationInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/priceSpecification/show.gsp
<%@ page import="com.shqiperia.entities.PriceSpecification" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'priceSpecification.label', default: 'PriceSpecification')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-priceSpecification" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-priceSpecification" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list priceSpecification">
			
				<g:if test="${priceSpecificationInstance?.additionalType}">
				<li class="fieldcontain">
					<span id="additionalType-label" class="property-label"><g:message code="priceSpecification.additionalType.label" default="Additional Type" /></span>
					
						<span class="property-value" aria-labelledby="additionalType-label"><g:fieldValue bean="${priceSpecificationInstance}" field="additionalType"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.alternateName}">
				<li class="fieldcontain">
					<span id="alternateName-label" class="property-label"><g:message code="priceSpecification.alternateName.label" default="Alternate Name" /></span>
					
						<span class="property-value" aria-labelledby="alternateName-label"><g:fieldValue bean="${priceSpecificationInstance}" field="alternateName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="priceSpecification.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${priceSpecificationInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.eligibleQuantity}">
				<li class="fieldcontain">
					<span id="eligibleQuantity-label" class="property-label"><g:message code="priceSpecification.eligibleQuantity.label" default="Eligible Quantity" /></span>
					
						<span class="property-value" aria-labelledby="eligibleQuantity-label"><g:link controller="quantitativeValue" action="show" id="${priceSpecificationInstance?.eligibleQuantity?.id}">${priceSpecificationInstance?.eligibleQuantity?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.eligibleTransactionVolume}">
				<li class="fieldcontain">
					<span id="eligibleTransactionVolume-label" class="property-label"><g:message code="priceSpecification.eligibleTransactionVolume.label" default="Eligible Transaction Volume" /></span>
					
						<span class="property-value" aria-labelledby="eligibleTransactionVolume-label"><g:link controller="priceSpecification" action="show" id="${priceSpecificationInstance?.eligibleTransactionVolume?.id}">${priceSpecificationInstance?.eligibleTransactionVolume?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.image}">
				<li class="fieldcontain">
					<span id="image-label" class="property-label"><g:message code="priceSpecification.image.label" default="Image" /></span>
					
						<span class="property-value" aria-labelledby="image-label"><g:fieldValue bean="${priceSpecificationInstance}" field="image"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.maxPrice}">
				<li class="fieldcontain">
					<span id="maxPrice-label" class="property-label"><g:message code="priceSpecification.maxPrice.label" default="Max Price" /></span>
					
						<span class="property-value" aria-labelledby="maxPrice-label"><g:fieldValue bean="${priceSpecificationInstance}" field="maxPrice"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.minPrice}">
				<li class="fieldcontain">
					<span id="minPrice-label" class="property-label"><g:message code="priceSpecification.minPrice.label" default="Min Price" /></span>
					
						<span class="property-value" aria-labelledby="minPrice-label"><g:fieldValue bean="${priceSpecificationInstance}" field="minPrice"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="priceSpecification.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${priceSpecificationInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.price}">
				<li class="fieldcontain">
					<span id="price-label" class="property-label"><g:message code="priceSpecification.price.label" default="Price" /></span>
					
						<span class="property-value" aria-labelledby="price-label"><g:fieldValue bean="${priceSpecificationInstance}" field="price"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.priceCurrency}">
				<li class="fieldcontain">
					<span id="priceCurrency-label" class="property-label"><g:message code="priceSpecification.priceCurrency.label" default="Price Currency" /></span>
					
						<span class="property-value" aria-labelledby="priceCurrency-label"><g:fieldValue bean="${priceSpecificationInstance}" field="priceCurrency"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.sameAs}">
				<li class="fieldcontain">
					<span id="sameAs-label" class="property-label"><g:message code="priceSpecification.sameAs.label" default="Same As" /></span>
					
						<span class="property-value" aria-labelledby="sameAs-label"><g:fieldValue bean="${priceSpecificationInstance}" field="sameAs"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.url}">
				<li class="fieldcontain">
					<span id="url-label" class="property-label"><g:message code="priceSpecification.url.label" default="Url" /></span>
					
						<span class="property-value" aria-labelledby="url-label"><g:fieldValue bean="${priceSpecificationInstance}" field="url"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.validFrom}">
				<li class="fieldcontain">
					<span id="validFrom-label" class="property-label"><g:message code="priceSpecification.validFrom.label" default="Valid From" /></span>
					
						<span class="property-value" aria-labelledby="validFrom-label"><g:formatDate date="${priceSpecificationInstance?.validFrom}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.validThrough}">
				<li class="fieldcontain">
					<span id="validThrough-label" class="property-label"><g:message code="priceSpecification.validThrough.label" default="Valid Through" /></span>
					
						<span class="property-value" aria-labelledby="validThrough-label"><g:formatDate date="${priceSpecificationInstance?.validThrough}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceSpecificationInstance?.valueAddedTaxIncluded}">
				<li class="fieldcontain">
					<span id="valueAddedTaxIncluded-label" class="property-label"><g:message code="priceSpecification.valueAddedTaxIncluded.label" default="Value Added Tax Included" /></span>
					
						<span class="property-value" aria-labelledby="valueAddedTaxIncluded-label"><g:formatBoolean boolean="${priceSpecificationInstance?.valueAddedTaxIncluded}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:priceSpecificationInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${priceSpecificationInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>